# Generated by Django 3.1.7 on 2021-04-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orgmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aim', models.TextField(blank=True, null=True)),
                ('portfolio_site', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
