# Generated by Django 3.1.7 on 2021-04-04 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awaremeapp', '0005_auto_20210404_1052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orgmodel',
            old_name='aim',
            new_name='mission',
        ),
    ]
