# Generated by Django 3.1.7 on 2021-04-04 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('awaremeapp', '0009_orgmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orgmodel',
            name='password',
        ),
        migrations.AlterField(
            model_name='orgmodel',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
