# Generated by Django 3.1.7 on 2021-04-04 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awaremeapp', '0010_auto_20210404_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orgmodel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='orgmodel',
            name='name',
        ),
    ]
