# Generated by Django 3.1.7 on 2021-04-04 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awaremeapp', '0011_auto_20210404_2130'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrgModel',
        ),
    ]
