# Generated by Django 3.1.7 on 2021-04-04 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awaremeapp', '0013_orgmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orgmodel',
            name='user',
        ),
    ]
