# Generated by Django 3.1.7 on 2021-04-05 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awaremeapp', '0015_orgmodel_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrgModel',
        ),
    ]
