# Generated by Django 3.1.7 on 2021-04-18 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awaremeapp', '0017_orgmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrgModel',
            new_name='OrgDetails',
        ),
    ]
