# Generated by Django 3.1.7 on 2021-04-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awaremeapp', '0018_auto_20210418_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('brief', models.TextField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=250, null=True)),
                ('locations', models.CharField(choices=[('Andhra_Pradesh', 'Andhra_Pradesh'), ('Arunachal_Pradesh', 'Arunachal_Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal_Pradesh', 'Himachal_Pradesh'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya_Pradesh', 'Madhya_Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('TamilNadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar_Pradesh', 'Uttar_Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West_Bengal', 'West_Bengal'), ('Andaman_Nicobar_Islands', 'Andaman_and_Nicobar_Islands'), ('Chandigarh', 'Chandigarh'), ('Dadra_Nagar_Haveli_and_Daman_Diu', 'Dadra_Nagar_Haveli_and_Daman_Diu'), ('Delhi', 'Delhi'), ('Jammu_and_Kashmir', 'Jammu_and_Kashmir'), ('Lakshadweep', 'Lakshadweep'), ('Puducherry', 'Puducherry'), ('Ladakh', 'Ladakh')], max_length=100)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('start_datetime', models.DateTimeField()),
            ],
        ),
        migrations.RenameModel(
            old_name='OrgDetails',
            new_name='OrgDetail',
        ),
    ]
