# Generated by Django 3.1.7 on 2021-05-01 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awaremeapp', '0021_auto_20210426_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgfeed',
            name='search',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
