# Generated by Django 3.1.7 on 2021-05-02 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awaremeapp', '0022_orgfeed_search'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orgdetail',
            name='name',
        ),
        migrations.RemoveField(
            model_name='orgfeed',
            name='search',
        ),
    ]
