# Generated by Django 3.1.7 on 2021-05-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awaremeapp', '0032_auto_20210503_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgdetail',
            name='profile_pic',
            field=models.ImageField(blank=True, default='awareme\\static\\images\\image_H2uXRm3.png', null=True, upload_to='awareme\\static\\images'),
        ),
    ]
