# Generated by Django 3.1.7 on 2021-05-04 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('awaremeapp', '0034_auto_20210503_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orgfeed',
            name='start_datetime',
        ),
        migrations.AddField(
            model_name='orgfeed',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='orgdetail',
            name='profile_pic',
            field=models.ImageField(default='default.png', null=True, upload_to='awareme\\static\\images'),
        ),
        migrations.CreateModel(
            name='FeedComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='awaremeapp.feedcomment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awaremeapp.orgfeed')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
