# Generated by Django 3.1.7 on 2021-05-06 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awaremeapp', '0035_auto_20210504_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgdetail',
            name='Contact',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
