# Generated by Django 3.1.7 on 2021-05-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awaremeapp', '0036_auto_20210506_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orgfeed',
            name='address',
        ),
        migrations.AlterField(
            model_name='orgfeed',
            name='locations',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
