# Generated by Django 3.1.7 on 2021-05-12 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awaremeapp', '0037_auto_20210507_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orgdetail',
            name='profile_pic',
        ),
    ]
